<h1>Determinações cadastradas</h1>
<div class="row">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Determinação</th>
                <th>Tipo</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            foreach ($this->determinacoes as $determinacao): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($determinacao->getDescricao()); ?></td>
                    <td><?php echo $this->escapeHtml($this->tipos[$determinacao->getTipo()]); ?></td>
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('patologia/determinacao', ['action' => 'save', 'id' => $determinacao->getId()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('patologia/determinacao', ['action' => 'delete', 'id' => $determinacao->getId()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-trash"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->determinacoes, 'Elastic', 'patologia/partial/paginator', ['route' => 'patologia/determinacao']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left"
       href="/patologia/determinacao/save">Novo registro</a>
</div>
