<?php
$form = $this->form;
$form->get('descricao')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite a descrição aqui'
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
]);
?>

<h1>Cadastro de determinações</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre
                    o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/patologia/determinacao" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>

                <?php echo $this->formLabel($form->get('descricao')); ?><br>
                <?php echo $this->formElement($form->get('descricao')); ?>
                <?php echo $this->formElementErrors($form->get('descricao')); ?>                  
                <br><br>

                <?php echo $this->formLabel($form->get('tipo')); ?><br>
                <?php echo $this->formElement($form->get('tipo')); ?>
                <?php echo $this->formElementErrors($form->get('tipo')); ?>                  
                <br><br>
                <?php echo $this->formElement($form->get('submit')); ?>

                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
