<?php
// $this->headStyle()->appendStyle('/css/select2.min.css');
$this->headScript()->appendFile('/js/select2.min.js', 'text/javascript');
$form = $this->form;

$form->get('numeroLaboratorio')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary',
    'value' => 'Continuar'
]);
?>

<h1>Análise - entrada de dados</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, selecione a amostra para iniciar a coleta de dados.<a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/patologia" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formLabel($form->get('numeroLaboratorio')); ?><br>
                <?php echo $this->formElement($form->get('numeroLaboratorio')); ?>
                <?php echo $this->formElementErrors($form->get('numeroLaboratorio')); ?>
                <?php echo $this->formElement($form->get('submit')); ?>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#numeroLaboratorio").select2({
        placeholder: "Selecione a amostra",
        allowClear: true
    });
</script>