<?php
$title = 'Excluir um registro';
$url   = $this->url('patologia/especie', ['action' => 'delete', 'id' => $especie->getId()]);
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>

<p>
    Deseja realmente excluir 
    "<?php echo $this->escapeHtml($especie->getDescricao()); ?>"
</p>

<form action="<?php echo $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $especie->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Sim" />
        <input type="submit" class="btn btn-success" name="del" value="Não" />
    </div>
</form>